const CATEGORIES = [
  { key: 'chat', label: '对话助手', color: '#2f7d5d' },
  { key: 'image', label: '图像创作', color: '#b35b3f' },
  { key: 'video', label: '视频创作', color: '#8b5aa8' },
  { key: 'audio', label: '音频创作', color: '#2e7394' },
  { key: 'coding', label: '编程开发', color: '#5c6ca3' },
  { key: 'office', label: '办公效率', color: '#4f8049' },
  { key: 'research', label: '搜索研究', color: '#a36a3c' },
  { key: 'design', label: '设计工具', color: '#b14b64' },
  { key: 'agent', label: 'AI Agent', color: '#447171' },
  { key: 'learning', label: '学习成长', color: '#7a6b4a' }
];

const TOOLS = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    category: 'chat',
    tags: ['海外', '免费额度'],
    desc: 'OpenAI 出品的全能对话助手，支持写作、翻译、编程与多模态理解。',
    url: 'https://chatgpt.com',
    color: '#10a37f',
    rating: 4.9,
    traffic: 98,
    added: '2024-06-01',
    price: '免费额度',
    features: ['长文本对话', '图片识别', '语音输入', '网页浏览'],
    hot: true
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'chat',
    tags: ['海外', '付费'],
    desc: 'Anthropic 出品，擅长长文档理解、代码生成与深度推理。',
    url: 'https://claude.ai',
    color: '#c15f3c',
    rating: 4.9,
    traffic: 94,
    added: '2024-06-08',
    price: '付费',
    features: ['超长上下文', '文档解析', '代码能力', 'Artifacts'],
    hot: true
  },
  {
    id: 'gemini',
    name: 'Gemini',
    category: 'chat',
    tags: ['海外', '免费额度'],
    desc: 'Google 多模态模型，与搜索、Gmail、文档等生态深度整合。',
    url: 'https://gemini.google.com',
    color: '#4285f4',
    rating: 4.7,
    traffic: 88,
    added: '2024-07-02',
    price: '免费额度',
    features: ['多模态', 'Google 生态', '实时信息'],
    hot: false
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'chat',
    tags: ['国产', '免费', '开源'],
    desc: '深度求索推出的开源大模型助手，推理能力强，性价比高。',
    url: 'https://chat.deepseek.com',
    color: '#4d6bfe',
    rating: 4.8,
    traffic: 92,
    added: '2025-01-20',
    price: '免费',
    features: ['深度推理', '代码能力', '联网搜索', '开放 API'],
    hot: true
  },
  {
    id: 'kimi',
    name: 'Kimi',
    category: 'chat',
    tags: ['国产', '免费额度'],
    desc: '月之暗面出品，擅长超长文本阅读、资料整理与深度问答。',
    url: 'https://kimi.moonshot.cn',
    color: '#2f2f2f',
    rating: 4.8,
    traffic: 87,
    added: '2024-08-12',
    price: '免费额度',
    features: ['长文本', '文件解析', '网页阅读'],
    hot: true
  },
  {
    id: 'doubao',
    name: '豆包',
    category: 'chat',
    tags: ['国产', '免费'],
    desc: '字节跳动推出的全能 AI 助手，支持写作、翻译、语音与图像。',
    url: 'https://www.doubao.com',
    color: '#3370ff',
    rating: 4.7,
    traffic: 89,
    added: '2024-09-05',
    price: '免费',
    features: ['全能对话', '语音', '图片理解', '插件'],
    hot: false
  },
  {
    id: 'qianwen',
    name: '通义千问',
    category: 'chat',
    tags: ['国产', '免费额度'],
    desc: '阿里云大模型助手，办公、学习与创作场景能力全面。',
    url: 'https://tongyi.aliyun.com',
    color: '#6a5cff',
    rating: 4.6,
    traffic: 80,
    added: '2024-07-20',
    price: '免费额度',
    features: ['全能助手', '文档', '代码', '插件'],
    hot: false
  },
  {
    id: 'wenxin',
    name: '文心一言',
    category: 'chat',
    tags: ['国产', '免费额度'],
    desc: '百度生成式 AI 助手，融合搜索、知识增强与多模态理解。',
    url: 'https://yiyan.baidu.com',
    color: '#2932e1',
    rating: 4.5,
    traffic: 78,
    added: '2024-07-11',
    price: '免费额度',
    features: ['知识问答', '创作', '图片理解'],
    hot: false
  },
  {
    id: 'zhipu',
    name: '智谱清言',
    category: 'chat',
    tags: ['国产', '免费额度'],
    desc: '智谱 AI 的对话助手，支持智能体、知识库问答与多模态能力。',
    url: 'https://chatglm.cn',
    color: '#1d8a8a',
    rating: 4.6,
    traffic: 76,
    added: '2024-08-01',
    price: '免费额度',
    features: ['智能体', '知识库', '代码'],
    hot: false
  },
  {
    id: 'xinghuo',
    name: '讯飞星火',
    category: 'chat',
    tags: ['国产', '免费额度'],
    desc: '科大讯飞大模型助手，语音识别与合成能力突出。',
    url: 'https://xinghuo.xfyun.cn',
    color: '#e8452c',
    rating: 4.5,
    traffic: 72,
    added: '2024-07-26',
    price: '免费额度',
    features: ['语音', '知识问答', '办公'],
    hot: false
  },
  {
    id: 'yuanbao',
    name: '腾讯元宝',
    category: 'chat',
    tags: ['国产', '免费'],
    desc: '腾讯推出的 AI 助手，接入微信生态与公众号内容。',
    url: 'https://yuanbao.tencent.com',
    color: '#0066ff',
    rating: 4.5,
    traffic: 75,
    added: '2025-03-18',
    price: '免费',
    features: ['微信生态', '文档', '语音'],
    hot: false
  },
  {
    id: 'grok',
    name: 'Grok',
    category: 'chat',
    tags: ['海外', '付费'],
    desc: 'xAI 出品，接入 X 实时信息，回答风格直接且带幽默感。',
    url: 'https://grok.com',
    color: '#2b2b2b',
    rating: 4.5,
    traffic: 70,
    added: '2025-02-14',
    price: '付费',
    features: ['实时信息', '图像生成', '多模态'],
    hot: false
  },
  {
    id: 'mistral',
    name: 'Mistral Le Chat',
    category: 'chat',
    tags: ['海外', '免费额度'],
    desc: '欧洲开源模型团队打造的对话助手，支持快速问答与代码。',
    url: 'https://chat.mistral.ai',
    color: '#ff7000',
    rating: 4.4,
    traffic: 62,
    added: '2025-01-05',
    price: '免费额度',
    features: ['快速问答', '代码', '开放模型'],
    hot: false
  },
  {
    id: 'poe',
    name: 'Poe',
    category: 'chat',
    tags: ['海外', '免费额度'],
    desc: '聚合多个主流 AI 模型的问答平台，一站对比不同助手。',
    url: 'https://poe.com',
    color: '#6a4cff',
    rating: 4.4,
    traffic: 65,
    added: '2024-09-18',
    price: '免费额度',
    features: ['多模型', 'Bot 广场', '对比'],
    hot: false
  },
  {
    id: 'character',
    name: 'Character.AI',
    category: 'chat',
    tags: ['海外', '免费额度'],
    desc: '与不同角色和人格对话，适合创意、陪聊与互动体验。',
    url: 'https://character.ai',
    color: '#9a6bff',
    rating: 4.3,
    traffic: 68,
    added: '2024-10-02',
    price: '免费额度',
    features: ['角色对话', '群聊', '创作'],
    hot: false
  },

  {
    id: 'midjourney',
    name: 'Midjourney',
    category: 'image',
    tags: ['海外', '付费'],
    desc: '以艺术感与画面质量著称的 AI 图像生成工具。',
    url: 'https://www.midjourney.com',
    color: '#1a1a1a',
    rating: 4.9,
    traffic: 93,
    added: '2024-06-03',
    price: '付费',
    features: ['高质感画面', '风格控制', '图像放大'],
    hot: true
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    category: 'image',
    tags: ['海外', '开源'],
    desc: '开源社区最活跃的扩散模型生态，模型与插件极为丰富。',
    url: 'https://stability.ai',
    color: '#9c35d2',
    rating: 4.8,
    traffic: 86,
    added: '2024-06-15',
    price: '开源',
    features: ['本地部署', '模型生态', 'ControlNet'],
    hot: false
  },
  {
    id: 'dalle',
    name: 'DALL·E 3',
    category: 'image',
    tags: ['海外', '付费'],
    desc: 'OpenAI 的图像生成模型，集成于 ChatGPT，理解自然语言提示。',
    url: 'https://openai.com/dall-e-3/',
    color: '#10a37f',
    rating: 4.7,
    traffic: 82,
    added: '2024-06-21',
    price: '付费',
    features: ['自然语言', '细节丰富', '安全过滤'],
    hot: false
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    category: 'image',
    tags: ['海外', '免费额度'],
    desc: '文字渲染能力突出的图像生成工具，适合海报与插画。',
    url: 'https://ideogram.ai',
    color: '#ff5a00',
    rating: 4.7,
    traffic: 78,
    added: '2024-07-08',
    price: '免费额度',
    features: ['文字排版', '风格多样', '放大'],
    hot: false
  },
  {
    id: 'leonardo',
    name: 'Leonardo.Ai',
    category: 'image',
    tags: ['海外', '免费额度'],
    desc: '面向创作工作流的图像生成与编辑平台，内置大量模型。',
    url: 'https://leonardo.ai',
    color: '#8f46ff',
    rating: 4.6,
    traffic: 74,
    added: '2024-08-05',
    price: '免费额度',
    features: ['模型库', '实时画布', '元素控制'],
    hot: false
  },
  {
    id: 'firefly',
    name: 'Adobe Firefly',
    category: 'image',
    tags: ['海外', '付费'],
    desc: 'Adobe 的创意生成模型，与 Photoshop、Illustrator 无缝衔接。',
    url: 'https://firefly.adobe.com',
    color: '#eb1000',
    rating: 4.6,
    traffic: 72,
    added: '2024-08-19',
    price: '付费',
    features: ['商业安全', 'PS 集成', '风格迁移'],
    hot: false
  },
  {
    id: 'jimeng',
    name: '即梦 AI',
    category: 'image',
    tags: ['国产', '免费额度'],
    desc: '字节跳动的 AI 创作平台，支持图像与视频生成。',
    url: 'https://jimeng.jianying.com',
    color: '#2b6cf6',
    rating: 4.7,
    traffic: 84,
    added: '2025-04-12',
    price: '免费额度',
    features: ['图像生成', '视频生成', '数字人'],
    hot: true
  },
  {
    id: 'yige',
    name: '文心一格',
    category: 'image',
    tags: ['国产', '免费额度'],
    desc: '百度的 AI 绘画平台，支持多种艺术风格与智能修图。',
    url: 'https://yige.baidu.com',
    color: '#3d63f5',
    rating: 4.4,
    traffic: 66,
    added: '2024-09-09',
    price: '免费额度',
    features: ['国风创作', '多风格', '智能编辑'],
    hot: false
  },
  {
    id: 'recraft',
    name: 'Recraft',
    category: 'image',
    tags: ['海外', '免费额度'],
    desc: '面向设计的矢量图像与品牌素材生成工具。',
    url: 'https://www.recraft.ai',
    color: '#ffb000',
    rating: 4.6,
    traffic: 70,
    added: '2025-02-01',
    price: '免费额度',
    features: ['矢量图', '品牌一致性', '样式控制'],
    hot: false
  },
  {
    id: 'flux',
    name: 'Flux',
    category: 'image',
    tags: ['海外', '开源'],
    desc: 'Black Forest Labs 的开源图像生成模型，细节与文字表现优秀。',
    url: 'https://blackforestlabs.ai',
    color: '#5b5b5b',
    rating: 4.7,
    traffic: 71,
    added: '2025-01-15',
    price: '开源',
    features: ['开源权重', '文字渲染', '本地部署'],
    hot: false
  },
  {
    id: 'krea',
    name: 'Krea',
    category: 'image',
    tags: ['海外', '免费额度'],
    desc: '实时 AI 画布与图像增强工具，适合边画边生成。',
    url: 'https://www.krea.ai',
    color: '#ff5f8f',
    rating: 4.5,
    traffic: 66,
    added: '2025-03-02',
    price: '免费额度',
    features: ['实时画布', '增强', '风格混合'],
    hot: false
  },
  {
    id: 'tensorart',
    name: 'TensorArt',
    category: 'image',
    tags: ['海外', '免费额度'],
    desc: '聚集大量模型与 LoRA 的 AI 绘画社区，支持在线生成。',
    url: 'https://tensor.art',
    color: '#5f6bff',
    rating: 4.5,
    traffic: 67,
    added: '2025-02-10',
    price: '免费额度',
    features: ['模型广场', 'LoRA', '工作流'],
    hot: false
  },
  {
    id: 'liblib',
    name: 'LiblibAI',
    category: 'image',
    tags: ['国产', '免费额度'],
    desc: '国内模型分享与在线生成社区，素材和教程丰富。',
    url: 'https://www.liblib.art',
    color: '#7b5cff',
    rating: 4.5,
    traffic: 65,
    added: '2025-04-01',
    price: '免费额度',
    features: ['模型社区', '在线生成', '教程'],
    hot: false
  },
  {
    id: 'removebg',
    name: 'Remove.bg',
    category: 'image',
    tags: ['海外', '免费额度'],
    desc: '一键抠图，快速去除图片背景，支持批量处理。',
    url: 'https://www.remove.bg',
    color: '#17a2b8',
    rating: 4.6,
    traffic: 73,
    added: '2024-10-11',
    price: '免费额度',
    features: ['一键抠图', '批量', 'API'],
    hot: false
  },
  {
    id: 'cleanup',
    name: 'Cleanup.pictures',
    category: 'image',
    tags: ['海外', '免费额度'],
    desc: '用画刷清除图片中不需要的人物、文字和杂物。',
    url: 'https://cleanup.pictures',
    color: '#30b596',
    rating: 4.5,
    traffic: 64,
    added: '2024-11-03',
    price: '免费额度',
    features: ['物体移除', '水印清除', '本地处理'],
    hot: false
  },

  {
    id: 'runway',
    name: 'Runway',
    category: 'video',
    tags: ['海外', '免费额度'],
    desc: '专业的 AI 视频生成与编辑工作台，支持多种视频模型。',
    url: 'https://runwayml.com',
    color: '#1a1a1a',
    rating: 4.8,
    traffic: 82,
    added: '2024-06-12',
    price: '免费额度',
    features: ['文本生视频', '图生视频', '视频编辑'],
    hot: false
  },
  {
    id: 'pika',
    name: 'Pika',
    category: 'video',
    tags: ['海外', '付费'],
    desc: '轻量易用的 AI 视频生成工具，擅长动态效果与风格化。',
    url: 'https://pika.art',
    color: '#ff4d8d',
    rating: 4.6,
    traffic: 74,
    added: '2024-07-19',
    price: '付费',
    features: ['文本生视频', '特效', '风格迁移'],
    hot: false
  },
  {
    id: 'luma',
    name: 'Luma Dream Machine',
    category: 'video',
    tags: ['海外', '免费额度'],
    desc: '高质量文本转视频与图像动效，运动自然流畅。',
    url: 'https://lumalabs.ai',
    color: '#5e4dff',
    rating: 4.6,
    traffic: 76,
    added: '2024-08-08',
    price: '免费额度',
    features: ['图生视频', '运动控制', '画质增强'],
    hot: false
  },
  {
    id: 'kling',
    name: '可灵 AI',
    category: 'video',
    tags: ['国产', '免费额度'],
    desc: '快手推出的视频生成大模型，画面连贯、动作自然。',
    url: 'https://klingai.kuaishou.com',
    color: '#ff6a00',
    rating: 4.8,
    traffic: 85,
    added: '2025-01-10',
    price: '免费额度',
    features: ['文本生视频', '图生视频', '数字人'],
    hot: true
  },
  {
    id: 'vidu',
    name: 'Vidu',
    category: 'video',
    tags: ['国产', '免费额度'],
    desc: '生数科技的视频生成模型，支持多主体一致性与可控生成。',
    url: 'https://www.vidu.cn',
    color: '#3a5bff',
    rating: 4.6,
    traffic: 73,
    added: '2025-03-20',
    price: '免费额度',
    features: ['多主体一致性', '参考图', '镜头控制'],
    hot: false
  },
  {
    id: 'hailuo',
    name: '海螺 AI',
    category: 'video',
    tags: ['国产', '免费额度'],
    desc: 'MiniMax 推出的视频生成与语音产品，创作体验轻快。',
    url: 'https://hailuoai.com',
    color: '#5a63ff',
    rating: 4.5,
    traffic: 68,
    added: '2025-04-18',
    price: '免费额度',
    features: ['视频生成', '配音', '智能助手'],
    hot: false
  },
  {
    id: 'sora',
    name: 'Sora',
    category: 'video',
    tags: ['海外', '付费'],
    desc: 'OpenAI 的视频生成模型，可生成一分钟级长视频。',
    url: 'https://sora.com',
    color: '#111111',
    rating: 4.7,
    traffic: 79,
    added: '2025-02-06',
    price: '付费',
    features: ['长视频', '图生视频', '多镜头'],
    hot: false
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    category: 'video',
    tags: ['海外', '付费'],
    desc: '数字人视频制作平台，支持多语言口型同步与克隆。',
    url: 'https://www.heygen.com',
    color: '#4f46e5',
    rating: 4.6,
    traffic: 70,
    added: '2024-09-15',
    price: '付费',
    features: ['数字人', '多语言', '口型同步'],
    hot: false
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    category: 'video',
    tags: ['海外', '付费'],
    desc: '企业级数字人视频生成工具，适合培训与营销内容。',
    url: 'https://www.synthesia.io',
    color: '#5a47ab',
    rating: 4.5,
    traffic: 64,
    added: '2024-10-06',
    price: '付费',
    features: ['企业模板', '数字人', '多语言'],
    hot: false
  },
  {
    id: 'did',
    name: 'D-ID',
    category: 'video',
    tags: ['海外', '付费'],
    desc: '照片说话、数字人视频与实时互动生成平台。',
    url: 'https://www.d-id.com',
    color: '#3d7bff',
    rating: 4.4,
    traffic: 60,
    added: '2024-11-20',
    price: '付费',
    features: ['照片说话', '实时互动', 'API'],
    hot: false
  },
  {
    id: 'capcut',
    name: '剪映',
    category: 'video',
    tags: ['国产', '免费'],
    desc: '国民级剪辑工具，内置智能成片、数字人与 AI 配音。',
    url: 'https://www.capcut.cn',
    color: '#2b2b2b',
    rating: 4.8,
    traffic: 90,
    added: '2024-08-25',
    price: '免费',
    features: ['智能成片', '数字人', 'AI 配音'],
    hot: false
  },
  {
    id: 'descript',
    name: 'Descript',
    category: 'video',
    tags: ['海外', '付费'],
    desc: '像编辑文档一样剪辑视频和播客，支持文字修改画面。',
    url: 'https://www.descript.com',
    color: '#e33d5a',
    rating: 4.5,
    traffic: 62,
    added: '2024-09-28',
    price: '付费',
    features: ['文稿剪辑', '录音棚', '口误消除'],
    hot: false
  },
  {
    id: 'kaiber',
    name: 'Kaiber',
    category: 'video',
    tags: ['海外', '付费'],
    desc: '音乐视频与创意短片生成工具，艺术风格独特。',
    url: 'https://kaiber.ai',
    color: '#7b2ff7',
    rating: 4.3,
    traffic: 54,
    added: '2025-01-22',
    price: '付费',
    features: ['音乐视频', '动画', '风格化'],
    hot: false
  },

  {
    id: 'suno',
    name: 'Suno',
    category: 'audio',
    tags: ['海外', '免费额度'],
    desc: '输入一句歌词即可生成完整歌曲，支持多种曲风。',
    url: 'https://suno.com',
    color: '#111111',
    rating: 4.8,
    traffic: 84,
    added: '2024-06-18',
    price: '免费额度',
    features: ['词曲生成', '多曲风', '人声'],
    hot: true
  },
  {
    id: 'udio',
    name: 'Udio',
    category: 'audio',
    tags: ['海外', '免费额度'],
    desc: '高质量 AI 音乐生成工具，编曲与混音效果出色。',
    url: 'https://www.udio.com',
    color: '#111111',
    rating: 4.6,
    traffic: 66,
    added: '2024-07-25',
    price: '免费额度',
    features: ['编曲生成', '人声', '风格扩展'],
    hot: false
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    category: 'audio',
    tags: ['海外', '免费额度'],
    desc: '自然拟真的语音合成与配音平台，支持声音克隆。',
    url: 'https://elevenlabs.io',
    color: '#111111',
    rating: 4.8,
    traffic: 80,
    added: '2024-07-05',
    price: '免费额度',
    features: ['语音合成', '声音克隆', '多语言'],
    hot: false
  },
  {
    id: 'moyin',
    name: '魔音工坊',
    category: 'audio',
    tags: ['国产', '免费额度'],
    desc: '面向自媒体的一站式 AI 配音工具，音色与情感丰富。',
    url: 'https://www.moyin.com',
    color: '#ff6a3d',
    rating: 4.5,
    traffic: 63,
    added: '2024-10-18',
    price: '免费额度',
    features: ['多音色', '情感配音', '口播'],
    hot: false
  },
  {
    id: 'ttsmaker',
    name: 'TTSMaker',
    category: 'audio',
    tags: ['国产', '免费'],
    desc: '免费在线文字转语音工具，支持多语言与多种音色。',
    url: 'https://ttsmaker.cn',
    color: '#00a6a6',
    rating: 4.5,
    traffic: 64,
    added: '2024-11-10',
    price: '免费',
    features: ['文字转语音', '多语言', '批量'],
    hot: false
  },
  {
    id: 'adobepodcast',
    name: 'Adobe Podcast',
    category: 'audio',
    tags: ['海外', '免费额度'],
    desc: '自动降噪、增强人声的播客与录音处理工具。',
    url: 'https://podcast.adobe.com',
    color: '#fa0f00',
    rating: 4.5,
    traffic: 60,
    added: '2024-09-03',
    price: '免费额度',
    features: ['降噪', '人声增强', '在线处理'],
    hot: false
  },
  {
    id: 'murf',
    name: 'Murf',
    category: 'audio',
    tags: ['海外', '付费'],
    desc: '商务配音与演示语音生成工具，支持语速和语调控制。',
    url: 'https://murf.ai',
    color: '#5a3fe0',
    rating: 4.4,
    traffic: 55,
    added: '2024-11-26',
    price: '付费',
    features: ['商务配音', '语调控制', '多语言'],
    hot: false
  },
  {
    id: 'lalal',
    name: 'LALAL.AI',
    category: 'audio',
    tags: ['海外', '付费'],
    desc: 'AI 人声与伴奏分离工具，音质清晰稳定。',
    url: 'https://www.lalal.ai',
    color: '#ff4a4a',
    rating: 4.5,
    traffic: 58,
    added: '2024-12-02',
    price: '付费',
    features: ['音轨分离', '人声提取', '伴奏'],
    hot: false
  },

  {
    id: 'copilot',
    name: 'GitHub Copilot',
    category: 'coding',
    tags: ['海外', '付费'],
    desc: '代码补全与 AI 编程助手，深度集成主流 IDE 和 GitHub。',
    url: 'https://github.com/features/copilot',
    color: '#2b3137',
    rating: 4.7,
    traffic: 83,
    added: '2024-06-05',
    price: '付费',
    features: ['代码补全', '聊天', 'PR 说明'],
    hot: false
  },
  {
    id: 'cursor',
    name: 'Cursor',
    category: 'coding',
    tags: ['海外', '免费额度'],
    desc: 'AI 优先的代码编辑器，可整库理解、搜索与重构。',
    url: 'https://www.cursor.com',
    color: '#1a1a1a',
    rating: 4.8,
    traffic: 88,
    added: '2024-08-10',
    price: '免费额度',
    features: ['整库理解', 'Composer', '多模型'],
    hot: true
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    category: 'coding',
    tags: ['海外', '免费额度'],
    desc: '智能 IDE，支持多文件 Agent 式编码与协作。',
    url: 'https://windsurf.com',
    color: '#18a0a0',
    rating: 4.6,
    traffic: 74,
    added: '2024-12-15',
    price: '免费额度',
    features: ['Agent 模式', '多文件', '上下文感知'],
    hot: false
  },
  {
    id: 'trae',
    name: 'Trae',
    category: 'coding',
    tags: ['国产', '免费'],
    desc: '字节跳动的 AI IDE，内置 Claude 与 GPT，适合中文用户。',
    url: 'https://www.trae.ai',
    color: '#2f6bff',
    rating: 4.6,
    traffic: 72,
    added: '2025-04-22',
    price: '免费',
    features: ['中文友好', '多模型', '整项目开发'],
    hot: false
  },
  {
    id: 'codeium',
    name: 'Codeium',
    category: 'coding',
    tags: ['海外', '免费额度'],
    desc: '免费好用的代码补全与聊天助手，支持多种 IDE。',
    url: 'https://codeium.com',
    color: '#09a6e2',
    rating: 4.5,
    traffic: 68,
    added: '2024-09-12',
    price: '免费额度',
    features: ['代码补全', '聊天', '多 IDE'],
    hot: false
  },
  {
    id: 'replit',
    name: 'Replit',
    category: 'coding',
    tags: ['海外', '免费额度'],
    desc: '云端开发平台，AI Agent 可直接从描述生成应用。',
    url: 'https://replit.com',
    color: '#f26207',
    rating: 4.6,
    traffic: 75,
    added: '2024-10-25',
    price: '免费额度',
    features: ['云端 IDE', 'Agent', '一键部署'],
    hot: false
  },
  {
    id: 'v0',
    name: 'v0',
    category: 'coding',
    tags: ['海外', '免费额度'],
    desc: 'Vercel 出品的 UI 生成工具，输入描述即可生成组件。',
    url: 'https://v0.dev',
    color: '#111111',
    rating: 4.7,
    traffic: 77,
    added: '2024-11-05',
    price: '免费额度',
    features: ['UI 生成', 'React', 'Tailwind'],
    hot: false
  },
  {
    id: 'lovable',
    name: 'Lovable',
    category: 'coding',
    tags: ['海外', '免费额度'],
    desc: '用自然语言快速构建全栈应用，支持数据库与部署。',
    url: 'https://lovable.dev',
    color: '#8a2be2',
    rating: 4.6,
    traffic: 71,
    added: '2025-01-30',
    price: '免费额度',
    features: ['全栈生成', '数据库', '部署'],
    hot: false
  },
  {
    id: 'bolt',
    name: 'Bolt.new',
    category: 'coding',
    tags: ['海外', '免费额度'],
    desc: '浏览器内用 AI 直接搭建可运行应用，所见即所得。',
    url: 'https://bolt.new',
    color: '#5b1ff5',
    rating: 4.6,
    traffic: 72,
    added: '2025-02-18',
    price: '免费额度',
    features: ['在线生成', '运行预览', '全栈'],
    hot: false
  },
  {
    id: 'lingma',
    name: '通义灵码',
    category: 'coding',
    tags: ['国产', '免费额度'],
    desc: '阿里云的智能编码助手，支持补全、问答与单元测试。',
    url: 'https://lingma.aliyun.com',
    color: '#6a5cff',
    rating: 4.5,
    traffic: 66,
    added: '2025-03-08',
    price: '免费额度',
    features: ['代码补全', '测试生成', '中文'],
    hot: false
  },
  {
    id: 'codegeex',
    name: 'CodeGeeX',
    category: 'coding',
    tags: ['国产', '开源'],
    desc: '智谱 AI 开源的编程助手与插件，支持多语言补全。',
    url: 'https://codegeex.cn',
    color: '#5f8aff',
    rating: 4.4,
    traffic: 58,
    added: '2024-11-18',
    price: '开源',
    features: ['代码补全', '多语言', '插件'],
    hot: false
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    category: 'coding',
    tags: ['海外', '付费'],
    desc: '注重隐私的企业级 AI 代码助手，支持本地模型。',
    url: 'https://www.tabnine.com',
    color: '#4c33ff',
    rating: 4.4,
    traffic: 55,
    added: '2024-12-09',
    price: '付费',
    features: ['隐私保护', '本地模型', '团队协作'],
    hot: false
  },
  {
    id: 'continue',
    name: 'Continue',
    category: 'coding',
    tags: ['海外', '开源'],
    desc: '开源 AI 代码助手，支持本地与云端模型自由切换。',
    url: 'https://continue.dev',
    color: '#111111',
    rating: 4.5,
    traffic: 60,
    added: '2025-01-08',
    price: '开源',
    features: ['开源', '本地模型', '自定义'],
    hot: false
  },
  {
    id: 'cline',
    name: 'Cline',
    category: 'coding',
    tags: ['海外', '开源'],
    desc: 'VS Code 里的开源 AI 编程 Agent，可自主读写文件。',
    url: 'https://cline.bot',
    color: '#7033ff',
    rating: 4.6,
    traffic: 63,
    added: '2025-03-25',
    price: '开源',
    features: ['自主编码', '终端操作', '开源'],
    hot: false
  },

  {
    id: 'notion',
    name: 'Notion AI',
    category: 'office',
    tags: ['海外', '付费'],
    desc: '知识库与 AI 写作问答深度结合，适合团队协作。',
    url: 'https://www.notion.so/product/ai',
    color: '#111111',
    rating: 4.7,
    traffic: 78,
    added: '2024-07-14',
    price: '付费',
    features: ['写作助手', '知识库问答', '自动化'],
    hot: false
  },
  {
    id: 'm365',
    name: 'Microsoft 365 Copilot',
    category: 'office',
    tags: ['海外', '付费'],
    desc: '接入 Word、Excel、PPT 和 Outlook 的 AI 助手。',
    url: 'https://www.microsoft.com/microsoft-365/copilot',
    color: '#d83b01',
    rating: 4.6,
    traffic: 72,
    added: '2024-08-14',
    price: '付费',
    features: ['Word', 'Excel', 'PPT', '会议'],
    hot: false
  },
  {
    id: 'wpsai',
    name: 'WPS AI',
    category: 'office',
    tags: ['国产', '免费额度'],
    desc: 'WPS 文档中的 AI 写作、排版与演示生成能力。',
    url: 'https://ai.wps.cn',
    color: '#0072ff',
    rating: 4.6,
    traffic: 76,
    added: '2024-09-01',
    price: '免费额度',
    features: ['智能写作', '排版', 'PPT 生成'],
    hot: false
  },
  {
    id: 'feishu',
    name: '飞书智能伙伴',
    category: 'office',
    tags: ['国产', '免费额度'],
    desc: '会议纪要、文档与消息场景中的 AI 助手。',
    url: 'https://www.feishu.cn/product/ai',
    color: '#3370ff',
    rating: 4.6,
    traffic: 70,
    added: '2024-10-20',
    price: '免费额度',
    features: ['会议纪要', '文档', '消息'],
    hot: false
  },
  {
    id: 'gamma',
    name: 'Gamma',
    category: 'office',
    tags: ['海外', '免费额度'],
    desc: '用一句话生成精美演示文稿，支持在线编辑分享。',
    url: 'https://gamma.app',
    color: '#9b30ff',
    rating: 4.6,
    traffic: 74,
    added: '2024-09-22',
    price: '免费额度',
    features: ['PPT 生成', '模板', '在线分享'],
    hot: false
  },
  {
    id: 'canva',
    name: 'Canva 魔法工作室',
    category: 'office',
    tags: ['海外', '免费额度'],
    desc: '设计平台内的一站式 AI 创作套件，海报、文案与视频。',
    url: 'https://www.canva.cn',
    color: '#00c4cc',
    rating: 4.7,
    traffic: 80,
    added: '2024-10-08',
    price: '免费额度',
    features: ['AI 设计', '文案', '视频'],
    hot: false
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    category: 'office',
    tags: ['海外', '免费额度'],
    desc: '英文写作检查与润色工具，覆盖邮件和文档。',
    url: 'https://www.grammarly.com',
    color: '#15c39a',
    rating: 4.7,
    traffic: 75,
    added: '2024-08-28',
    price: '免费额度',
    features: ['语法检查', '改写', '语气'],
    hot: false
  },
  {
    id: 'quillbot',
    name: 'QuillBot',
    category: 'office',
    tags: ['海外', '免费额度'],
    desc: '英文改写、摘要与语法检查工具，适合学术写作。',
    url: 'https://quillbot.com',
    color: '#7b68ee',
    rating: 4.6,
    traffic: 69,
    added: '2024-09-16',
    price: '免费额度',
    features: ['改写', '摘要', '引用'],
    hot: false
  },
  {
    id: 'otter',
    name: 'Otter.ai',
    category: 'office',
    tags: ['海外', '免费额度'],
    desc: '实时会议转写与笔记，自动生成摘要和行动项。',
    url: 'https://otter.ai',
    color: '#00a88f',
    rating: 4.5,
    traffic: 64,
    added: '2024-10-30',
    price: '免费额度',
    features: ['实时转写', '会议摘要', '协作'],
    hot: false
  },
  {
    id: 'fireflies',
    name: 'Fireflies.ai',
    category: 'office',
    tags: ['海外', '免费额度'],
    desc: '自动记录会议并生成摘要、行动项与关键词。',
    url: 'https://fireflies.ai',
    color: '#2b3bff',
    rating: 4.5,
    traffic: 61,
    added: '2024-12-12',
    price: '免费额度',
    features: ['会议记录', '摘要', '集成'],
    hot: false
  },
  {
    id: 'beautiful',
    name: 'Beautiful.ai',
    category: 'office',
    tags: ['海外', '付费'],
    desc: '自动排版的 AI 演示工具，让幻灯片保持整洁。',
    url: 'https://www.beautiful.ai',
    color: '#5a31f4',
    rating: 4.4,
    traffic: 56,
    added: '2024-11-08',
    price: '付费',
    features: ['自动排版', '智能模板', '团队'],
    hot: false
  },
  {
    id: 'iflyrec',
    name: '讯飞听见',
    category: 'office',
    tags: ['国产', '免费额度'],
    desc: '语音转文字与会议纪要工具，中文识别准确。',
    url: 'https://www.iflyrec.com',
    color: '#e8452c',
    rating: 4.6,
    traffic: 67,
    added: '2024-11-30',
    price: '免费额度',
    features: ['语音转写', '字幕', '会议纪要'],
    hot: false
  },
  {
    id: 'napkin',
    name: 'Napkin AI',
    category: 'office',
    tags: ['海外', '免费额度'],
    desc: '把文字快速变成可视化图表，适合报告与演示。',
    url: 'https://www.napkin.ai',
    color: '#ff7a00',
    rating: 4.5,
    traffic: 62,
    added: '2025-05-02',
    price: '免费额度',
    features: ['文字转图表', '样式', '导出'],
    hot: false
  },

  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'research',
    tags: ['海外', '免费额度'],
    desc: '带引用的 AI 搜索引擎，答案清晰且来源可查。',
    url: 'https://www.perplexity.ai',
    color: '#20808d',
    rating: 4.8,
    traffic: 85,
    added: '2024-06-10',
    price: '免费额度',
    features: ['实时搜索', '引用来源', '研究模式'],
    hot: true
  },
  {
    id: 'metaso',
    name: '秘塔 AI 搜索',
    category: 'research',
    tags: ['国产', '免费'],
    desc: '中文 AI 搜索，无广告并给出结构化答案与来源。',
    url: 'https://metaso.cn',
    color: '#111111',
    rating: 4.7,
    traffic: 79,
    added: '2024-09-25',
    price: '免费',
    features: ['无广告', '结构化答案', '思维导图'],
    hot: false
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    category: 'research',
    tags: ['海外', '免费'],
    desc: '上传资料后由 AI 归纳、问答并生成音频概览。',
    url: 'https://notebooklm.google.com',
    color: '#3a7afe',
    rating: 4.7,
    traffic: 73,
    added: '2024-10-15',
    price: '免费',
    features: ['文档问答', '音频概览', '引用'],
    hot: false
  },
  {
    id: 'consensus',
    name: 'Consensus',
    category: 'research',
    tags: ['海外', '付费'],
    desc: '基于学术论文的 AI 搜索与结论聚合。',
    url: 'https://consensus.app',
    color: '#00b5ad',
    rating: 4.5,
    traffic: 58,
    added: '2024-11-12',
    price: '付费',
    features: ['论文搜索', '结论聚合', '引用'],
    hot: false
  },
  {
    id: 'elicit',
    name: 'Elicit',
    category: 'research',
    tags: ['海外', '免费额度'],
    desc: '自动化文献综述与论文筛选，提取关键信息。',
    url: 'https://elicit.com',
    color: '#6c5ce7',
    rating: 4.5,
    traffic: 57,
    added: '2024-12-05',
    price: '免费额度',
    features: ['文献筛选', '摘要', '表格'],
    hot: false
  },
  {
    id: 'scispace',
    name: 'SciSpace',
    category: 'research',
    tags: ['海外', '免费额度'],
    desc: '论文解读、对比与引用管理，降低阅读门槛。',
    url: 'https://typeset.io',
    color: '#8a2be2',
    rating: 4.4,
    traffic: 55,
    added: '2025-01-18',
    price: '免费额度',
    features: ['论文解读', '对比', '引用'],
    hot: false
  },
  {
    id: 'scite',
    name: 'Scite',
    category: 'research',
    tags: ['海外', '付费'],
    desc: '展示论文被引语境，辅助判断研究可信度。',
    url: 'https://scite.ai',
    color: '#ff7043',
    rating: 4.4,
    traffic: 52,
    added: '2025-02-25',
    price: '付费',
    features: ['引文语境', '证据', '报告'],
    hot: false
  },
  {
    id: 'connectedpapers',
    name: 'Connected Papers',
    category: 'research',
    tags: ['海外', '免费'],
    desc: '用图谱探索论文之间的引用关系与研究脉络。',
    url: 'https://www.connectedpapers.com',
    color: '#17a2b8',
    rating: 4.5,
    traffic: 54,
    added: '2024-11-22',
    price: '免费',
    features: ['图谱', '引用关系', '文献调研'],
    hot: false
  },
  {
    id: 'semanticscholar',
    name: 'Semantic Scholar',
    category: 'research',
    tags: ['海外', '免费'],
    desc: '学术搜索与语义理解引擎，AI 提炼论文要点。',
    url: 'https://www.semanticscholar.org',
    color: '#1857b6',
    rating: 4.4,
    traffic: 56,
    added: '2024-12-18',
    price: '免费',
    features: ['学术搜索', 'TLDR', '引用'],
    hot: false
  },
  {
    id: 'tiangong',
    name: '天工 AI 搜索',
    category: 'research',
    tags: ['国产', '免费'],
    desc: '昆仑万维推出的 AI 搜索与问答，支持多轮追问。',
    url: 'https://www.tiangong.cn',
    color: '#2f54eb',
    rating: 4.3,
    traffic: 50,
    added: '2025-04-10',
    price: '免费',
    features: ['多轮问答', '搜索', '长文本'],
    hot: false
  },

  {
    id: 'figma',
    name: 'Figma AI',
    category: 'design',
    tags: ['海外', '免费额度'],
    desc: '设计协作平台内置的 AI 生成、整理与原型能力。',
    url: 'https://www.figma.com',
    color: '#1e1e1e',
    rating: 4.6,
    traffic: 69,
    added: '2024-10-05',
    price: '免费额度',
    features: ['AI 原型', '组件整理', '协作'],
    hot: false
  },
  {
    id: 'uizard',
    name: 'Uizard',
    category: 'design',
    tags: ['海外', '免费额度'],
    desc: '文字或草图秒变 UI 原型，适合快速验证想法。',
    url: 'https://uizard.io',
    color: '#6c63ff',
    rating: 4.4,
    traffic: 55,
    added: '2024-11-14',
    price: '免费额度',
    features: ['文字生 UI', '草图识别', '主题'],
    hot: false
  },
  {
    id: 'framer',
    name: 'Framer AI',
    category: 'design',
    tags: ['海外', '免费额度'],
    desc: '用提示词生成网站并在线发布，适合落地页。',
    url: 'https://www.framer.com',
    color: '#0055ff',
    rating: 4.6,
    traffic: 66,
    added: '2024-12-20',
    price: '免费额度',
    features: ['网站生成', '发布', '动效'],
    hot: false
  },
  {
    id: 'relume',
    name: 'Relume',
    category: 'design',
    tags: ['海外', '免费额度'],
    desc: '网站线框图与组件文案生成，帮助快速搭建站点。',
    url: 'https://www.relume.io',
    color: '#23a558',
    rating: 4.4,
    traffic: 52,
    added: '2025-01-26',
    price: '免费额度',
    features: ['线框图', '组件库', '文案'],
    hot: false
  },
  {
    id: 'khroma',
    name: 'Khroma',
    category: 'design',
    tags: ['海外', '免费'],
    desc: 'AI 配色方案生成器，快速组合品牌色板。',
    url: 'https://www.khroma.co',
    color: '#e0245e',
    rating: 4.4,
    traffic: 51,
    added: '2024-12-01',
    price: '免费',
    features: ['配色生成', '色板', '可访问性'],
    hot: false
  },
  {
    id: 'looka',
    name: 'Looka',
    category: 'design',
    tags: ['海外', '付费'],
    desc: 'AI 品牌 Logo 与视觉识别生成工具。',
    url: 'https://looka.com',
    color: '#2d2dff',
    rating: 4.4,
    traffic: 54,
    added: '2025-02-05',
    price: '付费',
    features: ['Logo 生成', '品牌套件', '商标'],
    hot: false
  },
  {
    id: 'brandmark',
    name: 'Brandmark',
    category: 'design',
    tags: ['海外', '付费'],
    desc: '基于品牌关键词自动生成 Logo 方案。',
    url: 'https://brandmark.io',
    color: '#111111',
    rating: 4.3,
    traffic: 49,
    added: '2025-02-28',
    price: '付费',
    features: ['Logo 生成', '配色', '商业授权'],
    hot: false
  },
  {
    id: 'coolors',
    name: 'Coolors',
    category: 'design',
    tags: ['海外', '免费'],
    desc: '配色工具，支持 AI 生成调色板与渐变。',
    url: 'https://coolors.co',
    color: '#0b0b0b',
    rating: 4.5,
    traffic: 57,
    added: '2024-10-12',
    price: '免费',
    features: ['调色板', '渐变', '对比度'],
    hot: false
  },

  {
    id: 'coze',
    name: 'Coze 扣子',
    category: 'agent',
    tags: ['国产', '免费'],
    desc: '字节跳动的一站式 AI Bot 开发平台，支持插件与知识库。',
    url: 'https://www.coze.cn',
    color: '#3370ff',
    rating: 4.7,
    traffic: 78,
    added: '2024-09-08',
    price: '免费',
    features: ['Bot 搭建', '插件', '工作流'],
    hot: true
  },
  {
    id: 'dify',
    name: 'Dify',
    category: 'agent',
    tags: ['海外', '开源'],
    desc: '开源 LLM 应用开发平台，支持工作流、RAG 与 Agent。',
    url: 'https://dify.ai',
    color: '#2f6bff',
    rating: 4.7,
    traffic: 76,
    added: '2024-10-18',
    price: '开源',
    features: ['工作流', 'RAG', '自部署'],
    hot: false
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'agent',
    tags: ['海外', '开源'],
    desc: '可视化自动化工作流，内置 AI 节点与数百集成。',
    url: 'https://n8n.io',
    color: '#ea4b71',
    rating: 4.6,
    traffic: 68,
    added: '2024-11-01',
    price: '开源',
    features: ['工作流', 'AI 节点', '自托管'],
    hot: false
  },
  {
    id: 'zapier',
    name: 'Zapier AI',
    category: 'agent',
    tags: ['海外', '付费'],
    desc: '连接上千款应用的自动化平台，AI 可理解任务意图。',
    url: 'https://zapier.com',
    color: '#ff4a00',
    rating: 4.5,
    traffic: 66,
    added: '2024-12-08',
    price: '付费',
    features: ['自动化', '应用连接', 'AI 任务'],
    hot: false
  },
  {
    id: 'make',
    name: 'Make',
    category: 'agent',
    tags: ['海外', '免费额度'],
    desc: '可视化场景自动化与集成平台，场景设计灵活。',
    url: 'https://www.make.com',
    color: '#ff5d3a',
    rating: 4.5,
    traffic: 62,
    added: '2025-01-12',
    price: '免费额度',
    features: ['场景自动化', '可视化', '集成'],
    hot: false
  },
  {
    id: 'flowise',
    name: 'Flowise',
    category: 'agent',
    tags: ['海外', '开源'],
    desc: '拖拽构建 LLM 应用与 Agent，无需复杂代码。',
    url: 'https://flowiseai.com',
    color: '#5b5bd6',
    rating: 4.5,
    traffic: 59,
    added: '2025-02-20',
    price: '开源',
    features: ['拖拽编排', 'Agent', 'RAG'],
    hot: false
  },
  {
    id: 'langchain',
    name: 'LangChain',
    category: 'agent',
    tags: ['海外', '开源'],
    desc: '构建大模型应用的主流开发框架，生态完善。',
    url: 'https://www.langchain.com',
    color: '#1c3c3c',
    rating: 4.6,
    traffic: 70,
    added: '2024-08-20',
    price: '开源',
    features: ['Agent 框架', '工具调用', '记忆'],
    hot: false
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'agent',
    tags: ['海外', '免费'],
    desc: '模型、数据集与 Demo 社区平台，AI 开发者必去。',
    url: 'https://huggingface.co',
    color: '#ffd21e',
    rating: 4.8,
    traffic: 82,
    added: '2024-07-30',
    price: '免费',
    features: ['模型库', '数据集', 'Spaces'],
    hot: false
  },
  {
    id: 'replicate',
    name: 'Replicate',
    category: 'agent',
    tags: ['海外', '免费额度'],
    desc: '一条 API 调用开源 AI 模型，按用量计费。',
    url: 'https://replicate.com',
    color: '#111111',
    rating: 4.5,
    traffic: 63,
    added: '2024-09-20',
    price: '免费额度',
    features: ['模型 API', '按量付费', '部署'],
    hot: false
  },
  {
    id: 'manus',
    name: 'Manus',
    category: 'agent',
    tags: ['国产', '免费额度'],
    desc: '通用 AI Agent，可自动完成复杂任务并交付成果。',
    url: 'https://manus.im',
    color: '#111111',
    rating: 4.6,
    traffic: 72,
    added: '2025-03-12',
    price: '免费额度',
    features: ['任务规划', '工具调用', '成果交付'],
    hot: false
  },
  {
    id: 'autogpt',
    name: 'AutoGPT',
    category: 'agent',
    tags: ['海外', '开源'],
    desc: '经典自主 AI Agent 项目，可设定目标自动执行。',
    url: 'https://agpt.co',
    color: '#2f5d8a',
    rating: 4.4,
    traffic: 60,
    added: '2024-08-05',
    price: '开源',
    features: ['自主任务', '开源', '多工具'],
    hot: false
  },

  {
    id: 'duolingo',
    name: 'Duolingo Max',
    category: 'learning',
    tags: ['海外', '付费'],
    desc: '多邻国 AI 对话与错误解释功能，让语言学习更沉浸。',
    url: 'https://www.duolingo.com',
    color: '#58cc02',
    rating: 4.6,
    traffic: 68,
    added: '2024-10-22',
    price: '付费',
    features: ['AI 对话', '错误解释', '角色扮演'],
    hot: false
  },
  {
    id: 'quizlet',
    name: 'Quizlet AI',
    category: 'learning',
    tags: ['海外', '免费额度'],
    desc: '用 AI 生成学习卡和测验，按知识点复习。',
    url: 'https://quizlet.com',
    color: '#4255ff',
    rating: 4.5,
    traffic: 62,
    added: '2024-11-16',
    price: '免费额度',
    features: ['学习卡', '测验', '错题'],
    hot: false
  },
  {
    id: 'khanmigo',
    name: 'Khanmigo',
    category: 'learning',
    tags: ['海外', '付费'],
    desc: '可汗学院的 AI 教学助手，引导式辅导学生。',
    url: 'https://www.khanmigo.ai',
    color: '#14bf96',
    rating: 4.5,
    traffic: 57,
    added: '2025-01-05',
    price: '付费',
    features: ['引导学习', '教师工具', '数学'],
    hot: false
  },
  {
    id: 'socratic',
    name: 'Socratic',
    category: 'learning',
    tags: ['海外', '免费'],
    desc: 'Google 出品的拍照解题助手，逐步解释过程。',
    url: 'https://socratic.org',
    color: '#4285f4',
    rating: 4.5,
    traffic: 61,
    added: '2024-12-11',
    price: '免费',
    features: ['拍照解题', '分步讲解', '多学科'],
    hot: false
  },
  {
    id: 'gauth',
    name: 'Gauth',
    category: 'learning',
    tags: ['海外', '免费额度'],
    desc: 'AI 拍照解题工具，覆盖数学、物理等多学科。',
    url: 'https://gauthmath.com',
    color: '#6c5ce7',
    rating: 4.4,
    traffic: 58,
    added: '2025-03-01',
    price: '免费额度',
    features: ['拍照解题', '快速解答', '多学科'],
    hot: false
  }
];
